FROM node:14-alpine

ARG NODE_APP_PORT=${NODE_APP_PORT}
ENV NODE_APP_PORT=${NODE_APP_PORT}

# Set the working directory
WORKDIR /app

# Copy package.json
COPY ./node-app/package*.json /app/

# Install dependencies
RUN npm install

# Add the source code to app
COPY  ./node-app /app/

# Run production build
CMD npm run express

EXPOSE ${NODE_APP_PORT}
