FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json
COPY ./express-app/package*.json /app/

# Install dependencies
RUN npm install

# Add the source code to app
COPY  ./express-app /app/

# Run production build
CMD npm run express

EXPOSE 3000
