FROM node:14-alpine

# Set the working directory
WORKDIR /app

# Copy package.json
COPY ./node-app/package*.json /app/

# Install dependencies
RUN npm install

# Add the source code to app
COPY  ./node-app /app/

# Run production build
CMD npm run express

EXPOSE 3000
