apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: angular-express
spec:
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: minikube:5000/angular-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
  namespace: angular-express
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: angular-app
